Quant_Project/django/config/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', lambda r: redirect('dashboard:portfolio'), name='index'),
    path('dashboard/', include('dashboard.urls', namespace='dashboard')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls)),]

Quant_Project/django/dashboard/urls.py
from django.urls import path
from dashboard import apis, views

app_name = 'dashboard'
urlpatterns = [
	path('api/factor/', apis.FactorAPIView.as_view(), name='factor_api'),
	path('api/market/', apis.MarketAPIView.as_view(), name='market_api'),
	path('api/portfolio/', apis.PortfolioAPIView.as_view(), name='portfolio_api'),

	path('factor/', views.factor, name='factor'),
	path('market/', views.market, name='market'),
	path('portfolio/', views.portfolio, name='portfolio'),
	path('presentation/', views.presentation, name='presentation'),
]

Quant_Project/django/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
# class User(AbstractUser):
#     pass

Quant_Project/django/core/models.py
from django.db import models

# Create your models here.

Quant_Project/django/dashboard/models.py
from django.db import models

# Create your models here.

Quant_Project/django/accounts/views.py
from django.shortcuts import render

# Create your views here.

Quant_Project/django/core/views.py
from django.shortcuts import render

# Create your views here.

Quant_Project/django/dashboard/views.py
from config.settings.base import BASE_DIR
from django.http import HttpResponse
from django.shortcuts import render
from django.templatetags.static import static
from django.urls import reverse

from dashboard.services import set_checkboxs_info

# Create your views here.
def factor(request):
	return render(request, 'dashboard/container/factor.html', {
        'app_name': 'factor',
        'checkboxs_info': set_checkboxs_info(),
    })


def market(request):
	return render(request, 'dashboard/container/market.html', {
        'app_name': 'market',
        'api_url': reverse('dashboard:market_api'),
        'checkboxs_info': set_checkboxs_info(),
    })


def portfolio(request):
    metric_first = {
        'returns': 'Total Returns',
        'cagr': 'CAGR',
    }

    metric_second = {
        'MDD': 'MDD',
        'MDD_duration': 'Underwater Period',
        'volatility': 'Anuallized Volatility',
    } 

    metric_third = {
        'sharp': 'Sharpe Ratio',
        'sortino': 'Sortino Ratio',
        'calmar': 'Calmar Ratio',
    }

    metric_last = {
        'CVaR_ratio': 'CVaR Ratio',
        'hit': 'Hit Ratio',
        'GtP': 'Gain-to-Pain'
    }
    
    return render(request, 'dashboard/container/portfolio.html', {
        'app_name': 'portfolio',
        'api_url': reverse('dashboard:portfolio_api'),
        'checkboxs_info': set_checkboxs_info(),
        'metric_first': metric_first,
        'metric_second': metric_second,
        'metric_third': metric_third,
        'metric_last': metric_last,
    })


def presentation(request):
    print(BASE_DIR)
    with open(BASE_DIR / 'static' / 'img' / 'presentation.pdf', 'rb') as pdf:
        response = HttpResponse(pdf.read(), content_type='application/pdf')
        response['Content-Disposition'] = 'filename=presentation..pdf'
        return response
    #  return render(request, 'dashboard/container/presentation.html')

Quant_Project/django/dashboard/templates/dashboard/components/metric.html
<div class="col-4 px-1">
    <div id="{{ key }}" class="chart-h-small shadow-sm bg-white border">
        <p class="chart-title">{{ value }}</p>

        <div class="d-flex flex-column">
            <div class="d-flex pt-2">
                <div class="flex-fill ps-1">Portfolio</div>
                <div class="flex-fill metric-value"></div>
            </div>

            <div class="d-flex pt-2">
                <div class="flex-fill ps-1">S&P500</div>
                <div class="flex-fill metric-value"></div>
            </div>
        </div>
    </div>
</div>

Quant_Project/django/dashboard/templates/dashboard/components/sidebar/checkbox.html
{% load static %}
{% load display_filter %}

<div class="mt-4h" 
    id="checkbox-{{ checkbox.group_name|lower|convert_blank_to_underline }}">
    <p class="checkbox-title">
        <span>{{ checkbox.group_name }}</span>

        {% if checkbox.is_multiple_check %}
            <a href="#" 
                id="check-all"
                class="fs-10 text-primary ms-2">
                All Select
            </a>
        {% endif %}
    </p>

    <div class="check-box-wrap bg-white shadow-sm border px-2">
        <div class="row p-2">
            {% for name in checkbox.input_name %}
                <div class="col-6 d-flex align-items-center p-1">
                    <input type="checkbox" 
                        value="{{ name|lower|convert_blank_to_underline }}"
                        name="{{ checkbox.group_name|lower|convert_blank_to_underline }}"
                        class="form-check-input mt-0 me-2 cursor-pointer {% if not checkbox.is_multiple_check %}checkbox-unique{% endif %}"
                        id="id_{{ name|lower|convert_blank_to_underline }}">

                    <label for="id_{{ name|lower|convert_blank_to_underline }}" 
                        class="form-check-label cursor-pointer fs-10">
                        {{ name }}
                    </label>
                </div>
            {% endfor %}
        </div>
    </div>
</div>

<script>
    function check_all()  {
        const checkAll = document.getElementById('check-all');
        const checkBoxs = checkAll.parentNode.nextElementSibling.querySelectorAll(
            '.form-check-input');

        checkAll.addEventListener('click', e => {
            e.preventDefault();
            checkBoxs.forEach((e) => { e.checked = true; });
        });
    };

    function checkbox_unique() {
        const checkBoxs = document.querySelectorAll(
            '#checkbox-{{ checkbox.group_name|lower|convert_blank_to_underline }} .checkbox-unique');

        checkBoxs.forEach((checkbox) => {
            checkbox.addEventListener('change', cb => {
                checkBoxs.forEach((e) => {
                    if (e != cb.target) { e.checked = false; }
                });
            })
        });
    };

    check_all();
    checkbox_unique();
</script>

Quant_Project/django/dashboard/templates/dashboard/components/sidebar/sidebar.html
{% load static %}

<!-- <div class="offcanvas offcanvas-end bg-light" 
    tabindex="-1" id="offcanvasRight" 
    aria-labelledby="offcanvasRightLabel">

    <div class="offcanvas-header">
        <h5 id="offcanvasRightLabel">
            Portfolio Strategy Laboratory
        </h5>

        <button type="button" 
            class="btn-close text-reset" 
            data-bs-dismiss="offcanvas" 
            aria-label="Close">
        </button>
    </div>

    <div class="offcanvas-body">
        <form action="">
            <div>
                <p class="check-box-title">
                    Time Range
                </p>
                <div>
                    <input type="date" name="trip-start" 
                        id="id_start" 
                        class="time-input rounded shadow-sm p-1 cursor-pointer">
                    ~
                    <input type="date" name="trip-start" 
                        id="id_end" 
                        class="time-input rounded shadow-sm p-1 cursor-pointer">
                </div>
            </div>
        
            {# for checkbox in checkboxs_info #}
                {# include 'core/components/sidebar/checkbox.html' with chekbox=checkbox #}
            {# endfor #}
        
            <div class="d-grid mt-4">
                <button type="submit" class="btn btn-primary shadow-sm">
                    Apply
                </button>
            </div>
        </form>
    </div>
</div> -->

<form id="select-options-form" action="">
    <div class="mt-2">
        <p class="check-box-title">
            Time Range
        </p>
        <div>
            <input type="date" name="start_date" 
                id="id_start" 
                class="time-input rounded shadow-sm p-1 cursor-pointer border">
            ~
            <input type="date" name="end_date" 
                id="id_end" 
                class="time-input rounded shadow-sm p-1 cursor-pointer border">
        </div>
    </div>

    {% for checkbox in checkboxs_info %}
        {% include 'dashboard/components/sidebar/checkbox.html' with chekbox=checkbox %}
    {% endfor %}

    <div class="d-grid mt-4">
        <button type="submit" class="btn btn-primary shadow-sm">
            Apply
        </button>
    </div>
</form>

Quant_Project/django/dashboard/templates/dashboard/container/factor.html
{% extends 'dashboard/container/layout.html' %}
{% load static %}


{% block chart_content %}
    <div class="row px-3">

        <div class="col-12 px-1">
            <div class="chart-h-full shadow-sm bg-white border">
                <p class="chart-title">
                    Yearly Return Ranking : Factors
                </p>
            </div>
        </div>

        <div class="col-12 pt-4">
            <div class="row">

                <div class="col-7 px-1">
                    <div class="row">
                        <div class="col-12">
                            <div class="chart-h-half shadow-sm bg-white border">
                                <p class="chart-title">
                                    Cumulative Return : Factors
                                </p>
                                <canvas id="cumulative-return-factors" height="110"></canvas>
                            </div>
                        </div>
        
                        <div class="col-12 mt-3">
                            <div class="chart-h-half shadow-sm bg-white border">
                                <p class="chart-title">
                                    1-year Rolling Factor Correlation
                                </p>
                                <canvas id="1-year-rolling-factor-correlation" height="110"></canvas>
                            </div>
                        </div>
                    </div>
                </div>
        
                <div class="col-5">
                    <div class="row">
                        <div class="col-12 px-1">
                            <div class="chart-h-half shadow-sm bg-white border">
                                <p class="chart-title">
                                    MECE
                                </p>
                            </div> 
                        </div>
        
                        <div class="col-12 mt-3">
                            <div class="row">
                                <div class="col-12">
                                    <div class="row">
                                        <div class="col-4 px-1">
                                            <div class="chart-h-small shadow-sm bg-white border">
                                                <p class="chart-title">
                                                    Beta
                                                </p>
                                                <div class="d-flex justify-content-center h-50 pt-2">
                                                    <p class="m-0 fs-6 text-danger align-self-center">20.5%</p>
                                                </div>
                                            </div>
                                        </div>
        
                                        <div class="col-4 px-1">
                                            <div class="chart-h-small shadow-sm bg-white border">
                                                <p class="chart-title">
                                                    Momentum
                                                </p>
                                                <div class="d-flex justify-content-center h-50 pt-2">
                                                    <p class="m-0 fs-6 text-danger align-self-center">20.5%</p>
                                                </div>
                                            </div>
                                        </div>
        
                                        <div class="col-4 px-1">
                                            <div class="chart-h-small shadow-sm bg-white border">
                                                <p class="chart-title">
                                                    Volatility
                                                </p>
                                                <div class="d-flex justify-content-center h-50 pt-2">
                                                    <p class="m-0 fs-6 text-danger align-self-center">20.5%</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
        
                                <div class="col-12 mt-3">
                                    <div class="row">
                                        <div class="col-4 px-1">
                                            <div class="chart-h-small shadow-sm bg-white border">
                                                <p class="chart-title">
                                                    Value
                                                </p>
                                                <div class="d-flex justify-content-center h-50 pt-2">
                                                    <p class="m-0 fs-6 text-danger align-self-center">20.5%</p>
                                                </div>
                                            </div>
                                        </div>
        
                                        <div class="col-4 px-1">
                                            <div class="chart-h-small shadow-sm bg-white border">
                                                <p class="chart-title">
                                                    Carry
                                                </p>
                                                <div class="d-flex justify-content-center h-50 pt-2">
                                                    <p class="m-0 fs-6 text-danger align-self-center">20.5%</p>
                                                </div>
                                            </div>
                                        </div>
        
                                        <div class="col-4 px-1">
                                            <div class="chart-h-small shadow-sm bg-white border">
                                                <p class="chart-title">
                                                    AI Forecasting
                                                </p>
                                                <div class="d-flex justify-content-center h-50 pt-2">
                                                    <p class="m-0 fs-6 text-danger align-self-center">20.5%</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
        
                            </div>
                        </div>
        
                    </div>
                </div>

            </div>
        </div>

    </div>
{% endblock %}

Quant_Project/django/dashboard/templates/dashboard/container/layout.html
{% extends 'container/base.html' %}

{% load static %}

{% block css %}
    <style>
        .chart-nav {
            display: flex;
            flex-wrap: wrap;
            padding-left: 0;
            margin-bottom: 0;
            list-style: none;
            border-bottom: 1px solid #dee2e6;
        }

        .chart-nav .chart-nav-link {
            margin-bottom: -1px;
            background: 0 0;
        }

        .chart-nav-link {
            display: block;
            padding: 0.5rem 1rem;
            color: #495057;
            text-decoration: none;
            transition: color .15s ease-in-out,background-color .15s ease-in-out,border-color .15s ease-in-out;
        }

        .chart-nav .chart-nav-link.active {
            color: #0d6efd;
            border-bottom: 2px solid #0d6efd;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="container">
        <div class="row">

            <div class="col-12 pt-5 pb-5">
                <ul class="chart-nav">
                    <li class="chart-nav-item">
                        <a href="{% url 'dashboard:portfolio' %}"
                            id="portfolio"
                            class="chart-nav-link fs-5">
                            Portfolio Universe
                        </a>
                    </li>
                    <li class="chart-nav-item">
                        <a href="{% url 'dashboard:factor' %}"
                            id="factor"
                            class="chart-nav-link fs-5">
                            Factor Universe
                        </a>
                    </li>
                    <li class="chart-nav-item">
                        <a href="{% url 'dashboard:market' %}"
                            id="market"
                            class="chart-nav-link fs-5">
                            Market Universe
                        </a>
                    </li>
                </ul>
            </div>

            <div class="row p-0 position-relative">
                {% include 'components/progress_loading.html' %}

                <div class="col-9">
                    {% block chart_content %}
                    {% endblock %}
                </div>
    
                <div id="sidebar" class="col-3 border bg-white">
                    {% include 'dashboard/components/sidebar/sidebar.html' %}
                </div>
            </div>            

        </div>
    </div>
{% endblock %}

{% block script %}
    <script src="{% static 'js/chart.js' %}"></script>
    <script>
        const chart = new Chart();
        axios.defaults.xsrfCookieName = 'csrftoken';
		axios.defaults.xsrfHeaderName = 'X-CSRFToken';

        document.getElementById('{{ app_name }}').classList.add('active');
    </script>
{% endblock %}

Quant_Project/django/dashboard/templates/dashboard/container/market.html
{% extends 'dashboard/container/layout.html' %}
{% load static %}


{% block chart_content %}
    <div class="row px-3">

        <div class="col-12">
            <div class="row">
                <div class="col-12 px-1">
                    <div class="chart-h-full shadow-sm bg-white border">
                        <p class="chart-title">
                            Market Regime Clustering
                        </p>
                        <div id="regime_clustering"></div>                    
                    </div>
                </div>

                <div class="col-12 pt-4">
                    <div class="row">
                        <div class="col-7 px-1">
                            <div class="row">
                                <div class="col-12">
                                    <div class="chart-h-half shadow-sm bg-white border">
                                        <p class="chart-title">
                                            Market Index Chart
                                        </p>
                                        <div id="index_chart"></div>
                                    </div>                            
                                </div>
        
                                <div class="col-12 mt-3">
                                    <div class="chart-h-half shadow-sm bg-white border">
                                        <p class="chart-title">
                                            Market Index Forecasting
                                        </p>
                                        <div id="index_forecasting"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
        
                        <div class="col-5 px-1">
                            <div class="row">
                                <div class="col-12">
                                    <div class="chart-h-half shadow-sm bg-white border">
                                        <p class="chart-title">
                                            Heatmap : Market Regime - Factor Return
                                        </p>
                                        <div id="market_regime"></div>
                                    </div>
                                </div>
        
                                <div class="col-12 mt-3">
                                    <div class="chart-h-half shadow-sm bg-white border">
                                        <p class="chart-title">
                                            Heatmap : Economic Growth - Factor Return
                                        </p>
                                        <div id="economic_growth"></div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script>
        chart.requestGet('{{ api_url }}');
        chart.requestPost('{{ api_url }}');
    </script>
{% endblock %}

Quant_Project/django/dashboard/templates/dashboard/container/portfolio.html
{% extends 'dashboard/container/layout.html' %}
{% load static %}


{% block chart_content %}
    <div class="row px-3">

        <div class="col-12 px-1">
            <div class="chart-h-full shadow-sm bg-white border">
                <p class="chart-title">
                    Cumulative Return: Portfolilo vs S&P500
                </p>
                <div id="cumulative"></div>
            </div>
        </div>

        <div class="col-12 pt-4">
            <div class="row">
                <div class="col-7 px-1">
                    <div class="row">
                        <div class="col-12">
                            <div class="chart-h-half shadow-sm bg-white border">
                                <p class="chart-title">
                                    MDD: Portfolilo vs S&P500
                                </p>
                                <div id="mdd"></div>
                            </div>
                            
                        </div>
                        <div class="col-12 mt-3">
                            <div class="chart-h-half shadow-sm bg-white border">
                                <p class="chart-title">
                                    1-year Rolling Sharp Ratio
                                </p>
                                <div id="rolling_sharp_ratio"></div>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-5">
                    <div class="row">

                        <div class="col-12 px-1">
                            <div class="chart-h-quarter d-flex flex-column shadow-sm bg-white border">
                                <div class="d-flex pb-1">
                                    <div class="col-4"></div>
                                    <div class="col-4 chart-title border-0 text-center">
                                        My Portfolio
                                    </div>
                                    <div class="col-4 chart-title border-0 text-center">
                                        S&P 500
                                    </div>
                                </div>

                                <div class="d-flex pb-1">
                                    <div class="col-4 chart-title border-0">
                                        Total Return
                                    </div>
                                    <div id="Portfolilo-returns" class="col-4 text-center"></div>
                                    <div id="S&P500-returns" class="col-4 text-center"></div>
                                </div>

                                <div class="d-flex pb-1">
                                    <div class="col-4 chart-title border-0">
                                        CAGR
                                    </div>
                                    <div id="Portfolilo-CAGR" class="col-4 text-center"></div>
                                    <div id="S&P500-CAGR" class="col-4 text-center"></div>
                                </div>
                            </div>
                        </div>

                        <div class="col-12 mt-4">
                            <div class="row">
                                {% for key, value in metric_second.items %}
                                    {% include 'dashboard/components/metric.html' with key=key value=value %}
                                {% endfor %}
                            </div>

                            <div class="row mt-4">
                                {% for key, value in metric_third.items %}
                                    {% include 'dashboard/components/metric.html' with key=key value=value %}
                                {% endfor %}
                            </div>

                            
                            <div class="row mt-4">
                                {% for key, value in metric_last.items %}
                                    {% include 'dashboard/components/metric.html' with key=key value=value %}
                                {% endfor %}
                            </div>
                            
                        </div>
                    </div>
                </div>
            </div>  
        </div>

    </div>
{% endblock %}

{% block script %}
    {{ block.super }}
    <script>
        chart.requestGet('{{ api_url }}');
        chart.requestPost('{{ api_url }}');
    </script>
{% endblock %}

Quant_Project/django/templates/components/footer.html
<footer class="text-muted py-5">
    <div class="container">
        <!-- <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p> -->
        <p class="mb-1">Album example is © Bootstrap, but please download and customize it for yourself!</p>
        <p class="mb-0">
            New to Bootstrap? 
            <a href="/">Visit the homepage</a> 
            or read our 
            <a href="/docs/5.1/getting-started/introduction/">getting started guide</a>.
        </p>
    </div>
</footer>

Quant_Project/django/templates/components/navbar.html
<nav class="navbar navbar-expand-xl navbar-dark bg-dark sticky-top" aria-label="Sixth navbar example">
    <div class="container-fluid">
        <a class="navbar-brand ps-3" href="#">Quant Project</a>
        <button class="navbar-toggler" 
            type="button" 
            data-bs-toggle="collapse" 
            data-bs-target="#navbarsExample06" 
            aria-controls="navbarsExample06" 
            aria-expanded="false" 
            aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExample06">
            <ul class="navbar-nav me-auto mb-2 mb-xl-0">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:portfolio' %}">
                        Dashboard
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'dashboard:presentation' %}" target="_blank">
                        Presentation
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>

Quant_Project/django/templates/components/progress_loading.html
{% load static %}

<style>
    .progress-loading {
			position: absolute;
			top: 0;
			left: 0;
			height: 100%;
			width: 100%;
			background-color: #fff;
			opacity: .8;
            z-index: 100;
		}
		.progress-loading img {
			margin: 0;
			position: absolute;
			top: 50%;
			left: 50%;
			transform: translate(-50%, -50%);
            z-index: 100;
		}
</style>

<div class="progress-loading text-center">
	<img src="{% static 'img/progressbar.gif' %}" alt="progressbar">
</div>

Quant_Project/django/templates/container/base.html
{% load static %}

<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0"> -->
        <link rel="stylesheet"  href="{% static 'css/bootstrap5/bootstrap5.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
        {% block css %}
        {% endblock %}

        <title>
            {% block title %}
                Quant
            {% endblock %}
        </title>
    </head>
    <body class="position-relative">
        {% include 'components/navbar.html' %}

        <div id="main" class="bg-light pb-5 border">
            {% block content %}
            {% endblock %}
        </div>

        {% include 'components/footer.html' %}

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
            crossorigin="anonymous">
        </script>
        <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/apexcharts"></script>
        <!-- <script src="https://cdn.jsdelivr.net/npm/chart.js"></script> -->
        <!-- <script src="https://cdn.plot.ly/plotly-2.17.1.min.js"></script> -->
        <script>
            // 인터넷 익스플로러 block
            if (/MSIE \d|Trident.*rv:/.test(navigator.userAgent)) {
                window.location = 'microsoft-edge:' + window.location;
                setTimeout(function () {
                    window.location = 'https://go.microsoft.com/fwlink/?linkid=2135547';
                }, 1);
            }
        </script>

        {% block script %}
        {% endblock %}
    </body>
</html>